---

- name: Install gcc
  apt:
    pkg: ['build-essential', 'libssl-dev']
    state: latest

- name: Install Avahi Developer Packages
  apt: pkg=libavahi-compat-libdnssd-dev

- name: Create Download Directory
  file: name=/var/lib/downloads state=directory mode=0755 owner=root group=root

- name: Download Node.js
  get_url: url={{ _nodejs.download_url }} dest="/var/lib/downloads/nodejs.tgz"
  register: download

- name: Create Unpack Directory
  file: name=/opt/nodejs state=directory mode=0755 owner=root group=root

- name: Unpack Download
  unarchive: src="/var/lib/downloads/nodejs.tgz" dest=/opt/nodejs mode=0755 owner=root group=root copy=no
  when: download is changed

- name: Install Node.js Active Alternative
  command: update-alternatives --install "/usr/bin/{{ item }}" {{ item }} /opt/nodejs/{{ _nodejs.version }}/bin/{{ item }} 1000
  with_items:
    - node
    - npm

- name: Set Installed Node.js Active Alternative
  command: update-alternatives --set {{ item }} /opt/nodejs/{{ _nodejs.version }}/bin/{{ item }}
  with_items:
    - node
    - npm

