---

- name: Update Apt Repositories
  apt: update_cache=yes upgrade=yes
  when: apt_update|default(False)|bool

- name: Install Base Packages
  apt: name={{ _base.packages }} state=latest force=yes

- name: Set Default Target to Multi-User
  command: systemctl set-default multi-user.target

- name: Set Timezone
  copy: content='Europe/Berlin\n' dest=/etc/timezone owner=root group=root mode=0644 backup=no
  notify: Restart NTP

- name: Reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Set locale
  lineinfile: dest=/etc/locale.gen regexp="^# de_DE.UTF-8" line="de_DE.UTF-8 UTF-8"

- name: Generate locales
  command: locale-gen

